
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = 
	esp32_exception_decoder
	default
	time
upload_protocol = esptool
upload_speed = 1500000
board_build.filesystem = littlefs
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
	-O2
platform_packages = 
	tool-esptoolpy
	tool-mklittlefs
board_upload.erase_flash = false
lib_ldf_mode = chain
lib_ignore = 
	RPAsyncTCP
lib_extra_dirs = 
	C:\Users\Mathieu\Documents\Arduino\libraries\Mathieu_util
lib_deps = 
	esp32async/ESPAsyncWebServer@*
	esp32async/AsyncTCP@*
	bblanchon/ArduinoJson@*
	# bodmer/TFT_eSPI #do not use this one, it's limited and the screen seems off
	lovyan03/LovyanGFX
	paulstoffregen/XPT2046_Touchscreen
